# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(425, 459)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.text1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.text1.setGeometry(QtCore.QRect(20, 10, 391, 41))
        self.text1.setObjectName("text1")
        self.text2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.text2.setGeometry(QtCore.QRect(0, 60, 361, 61))
        self.text2.setObjectName("text2")
        self.text3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.text3.setGeometry(QtCore.QRect(200, 130, 221, 41))
        self.text3.setObjectName("text3")
        self.confirmButton = QtWidgets.QPushButton(self.centralwidget)
        self.confirmButton.setGeometry(QtCore.QRect(170, 400, 88, 34))
        self.confirmButton.setObjectName("confirmButton")
        self.confirmText = QtWidgets.QTextBrowser(self.centralwidget)
        self.confirmText.setGeometry(QtCore.QRect(20, 270, 381, 51))
        self.confirmText.setObjectName("confirmText")
        self.confirmTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.confirmTextEdit.setGeometry(QtCore.QRect(13, 326, 401, 51))
        self.confirmTextEdit.setObjectName("confirmTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.text1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Добро пожаловать в </span><span style=\" font-size:14pt; text-decoration: underline;\">TurtleConstructor</span></p></body></html>"))
        self.text2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">...Или <span style=\" font-weight:600; font-style:italic;\">TC, </span>сдесь *кхм*, можно использовать конструктор.</p></body></html>"))
        self.text3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">И он работает на </span><span style=\" font-size:12pt; font-weight:600; font-style:italic; text-decoration: underline;\">Turtle</span></p></body></html>"))
        self.confirmButton.setText(_translate("MainWindow", "Проверить"))
        self.confirmText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">А теперь напишите: <span style=\" text-decoration: underline;\">Я хочу просто потратить ваше время в пустую заставляя вас писать этот текст :)</span></p></body></html>"))
